---
title: "census-scripts"
author: "Rob Mitchell"
date: "9/6/2021"
output: html_document
---



```{r, echo=FALSE}
# This chunk is just to make it possible to shrink the typeface in succeeding chunks. 
#Mainly this will be used for the crosstabs.

def.chunk.hook <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\\", options$size, "\n\n", x, "\n\n \\normalsize"), x)
})
```

## Initialize
```{r initialize}
options(gsubfn.engine = "R")
packages <-
  c(
    "tidyverse",
    "dplyr",
    "data.table",
    "devtools",
    "DataExplorer",
  )
install.packages(setdiff(packages, rownames(installed.packages())))
for (package in packages) {
  library(package, character.only = TRUE)
}

```

```{r location of files}
# -----------------------------
# Specify location of the files
# -----------------------------
header_file_path <- "./nygeo2020.pl"
part1_file_path  <- "./ny000012020.pl"
part2_file_path  <- "./ny000022020.pl"
part3_file_path  <- "./ny000032020.pl"

```

```{r import data}
# -----------------------------
# Import the data
# -----------------------------
header <- read.delim(header_file_path, header=FALSE, colClasses="character", sep="|")
part1  <- read.delim(part1_file_path,  header=FALSE, colClasses="character", sep="|")
part2  <- read.delim(part2_file_path,  header=FALSE, colClasses="character", sep="|")
part3  <- read.delim(part3_file_path,  header=FALSE, colClasses="character", sep="|")

```

```{r assign colnames}

colnames(header) <- c("FILEID", "STUSAB", "SUMLEV", "GEOVAR", "GEOCOMP", "CHARITER", "CIFSN", "LOGRECNO", "GEOID", 
  "GEOCODE", "REGION", "DIVISION", "STATE", "STATENS", "COUNTY", "COUNTYCC", "COUNTYNS", "COUSUB",
  "COUSUBCC", "COUSUBNS", "SUBMCD", "SUBMCDCC", "SUBMCDNS", "ESTATE", "ESTATECC", "ESTATENS", 
  "CONCIT", "CONCITCC", "CONCITNS", "PLACE", "PLACECC", "PLACENS", "TRACT", "BLKGRP", "BLOCK", 
  "AIANHH", "AIHHTLI", "AIANHHFP", "AIANHHCC", "AIANHHNS", "AITS", "AITSFP", "AITSCC", "AITSNS",
  "TTRACT", "TBLKGRP", "ANRC", "ANRCCC", "ANRCNS", "CBSA", "MEMI", "CSA", "METDIV", "NECTA",
  "NMEMI", "CNECTA", "NECTADIV", "CBSAPCI", "NECTAPCI", "UA", "UATYPE", "UR", "CD116", "CD118",
  "CD119", "CD120", "CD121", "SLDU18", "SLDU22", "SLDU24", "SLDU26", "SLDU28", "SLDL18", "SLDL22",
  "SLDL24", "SLDL26", "SLDL28", "VTD", "VTDI", "ZCTA", "SDELM", "SDSEC", "SDUNI", "PUMA", "AREALAND",
  "AREAWATR", "BASENAME", "NAME", "FUNCSTAT", "GCUNI", "POP100", "HU100", "INTPTLAT", "INTPTLON", 
  "LSADC", "PARTFLAG", "UGA")
colnames(part1) <- c("FILEID", "STUSAB", "CHARITER", "CIFSN", "LOGRECNO", 
                     paste0("P00", c(10001:10071, 20001:20073)))
colnames(part2) <- c("FILEID", "STUSAB", "CHARITER", "CIFSN", "LOGRECNO", 
                     paste0("P00", c(30001:30071, 40001:40073)), 
                     paste0("H00", 10001:10003))
colnames(part3) <- c("FILEID", "STUSAB", "CHARITER", "CIFSN", "LOGRECNO",
                     paste0("P00", 50001:50010))


```


```{r merge data}
# -----------------------------
# Merge the data
# -----------------------------
combine <- Reduce(function(x,y) {merge(x, y, by=c("LOGRECNO", "STUSAB", "FILEID", "CHARITER"))}, list(header[,-7], part1[,-4], part2[,-4], part3))

# -----------------------------
# Order the data
# -----------------------------
combine <- combine[order(combine$LOGRECNO), c("FILEID", "STUSAB", "SUMLEV", "GEOVAR", "GEOCOMP", "CHARITER", "CIFSN", "LOGRECNO", "GEOID", "GEOCODE", "REGION", "DIVISION", "STATE", "STATENS", "COUNTY", "COUNTYCC", "COUNTYNS", "COUSUB", "COUSUBCC", "COUSUBNS", "SUBMCD", "SUBMCDCC", "SUBMCDNS", "ESTATE", "ESTATECC", "ESTATENS", 
"CONCIT", "CONCITCC", "CONCITNS", "PLACE", "PLACECC", "PLACENS", "TRACT", "BLKGRP", "BLOCK", 
"AIANHH", "AIHHTLI", "AIANHHFP", "AIANHHCC", "AIANHHNS", "AITS", "AITSFP", "AITSCC", "AITSNS",
"TTRACT", "TBLKGRP", "ANRC", "ANRCCC", "ANRCNS", "CBSA", "MEMI", "CSA", "METDIV", "NECTA",
"NMEMI", "CNECTA", "NECTADIV", "CBSAPCI", "NECTAPCI", "UA", "UATYPE", "UR", "CD116", "CD118",
"CD119", "CD120", "CD121", "SLDU18", "SLDU22", "SLDU24", "SLDU26", "SLDU28", "SLDL18", "SLDL22",
"SLDL24", "SLDL26", "SLDL28", "VTD", "VTDI", "ZCTA", "SDELM", "SDSEC", "SDUNI", "PUMA", "AREALAND",
"AREAWATR", "BASENAME", "NAME", "FUNCSTAT", "GCUNI", "POP100", "HU100", "INTPTLAT", "INTPTLON", 
"LSADC", "PARTFLAG", "UGA", 
  paste0("P00", c(10001:10071, 20001:20073)), 
  paste0("P00", c(30001:30071, 40001:40073)), 
  paste0("H00", 10001:10003), paste0("P00", 50001:50010))]
  rownames(combine) <- 1:nrow(combine)

```

```{r header info}
head(combine)

```


```{r cutdown}

cutdown <- combine %>%
    select(GEOID, P0010001, P0010002, P0010003, P0010004, P0010005, P0010006, P0010007, P0010008, P0010009, P0020002, P0020003, P0030001, P0030002, P0030003, P0030004, P0030005, P0030006, P0030007, P0030008, P0030009, P0040002, H0010001, H0010002, H0010003, P0050001, P0050002, P0050007, TRACT, BLOCK, BLKGRP, PLACENS, PLACE)

dim(cutdown)

```


```{r summary} 
cn <- cutdown

cn$P0010001 <- as.numeric(cutdown$P0010001)
cn$P0010002 <- as.numeric(cutdown$P0010002)
cn$P0010003 <- as.numeric(cutdown$P0010003)
cn$P0010004 <- as.numeric(cutdown$P0010004)
cn$P0010005 <- as.numeric(cutdown$P0010005)
cn$P0010006 <- as.numeric(cutdown$P0010006)
cn$P0010007 <- as.numeric(cutdown$P0010007)
cn$P0010008 <- as.numeric(cutdown$P0010008)
cn$P0010009 <- as.numeric(cutdown$P0010009)
cn$P0020002 <- as.numeric(cutdown$P0020002)
cn$P0020003 <- as.numeric(cutdown$P0020003)
cn$P0030001 <- as.numeric(cutdown$P0030001)
cn$P0030002 <- as.numeric(cutdown$P0030002)
cn$P0030003 <- as.numeric(cutdown$P0030003)
cn$P0030004 <- as.numeric(cutdown$P0030004)
cn$P0030005 <- as.numeric(cutdown$P0030005)
cn$P0030006 <- as.numeric(cutdown$P0030006)
cn$P0030007 <- as.numeric(cutdown$P0030007)
cn$P0030008 <- as.numeric(cutdown$P0030008)
cn$P0030009 <- as.numeric(cutdown$P0030009)
cn$P0040002 <- as.numeric(cutdown$P0040002)
cn$H0010001 <- as.numeric(cutdown$H0010001)
cn$H0010002 <- as.numeric(cutdown$H0010002)
cn$H0010003 <- as.numeric(cutdown$H0010003)
cn$P0050001 <- as.numeric(cutdown$P0050001)
cn$P0050002 <- as.numeric(cutdown$P0050002)
cn$P0050007 <- as.numeric(cutdown$P0050007)

summary(cutNumbers)

```

```{r summary 2}
summary(cn)

```