---
title: "census-mizzou"
author: "Rob Mitchell"
date: "10/10/2021"
output: html_document
---

```{r, echo=FALSE}
# This chunk is just to make it possible to shrink the typeface in succeeding chunks. 
#Mainly this will be used for the crosstabs.

def.chunk.hook <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\\", options$size, "\n\n", x, "\n\n \\normalsize"), x)
})
```

## Initialize
```{r initialize}
options(gsubfn.engine = "R")
packages <-
  c(
    "tidyverse",
    "dplyr",
    "data.table",
    "devtools",
    "DataExplorer",
    "ggplot2",
    "tigris",
    "leaflet"
  )
install.packages(setdiff(packages, rownames(installed.packages())))
for (package in packages) {
  library(package, character.only = TRUE)
}

```

```{r location of files}
# -----------------------------
# Specify location of the files
# -----------------------------
twenty_header_file_path <- "./mogeo2020.pl"
twenty_part1_file_path  <- "./mo000012020.pl"
twenty_part2_file_path  <- "./mo000022020.pl"
twenty_part3_file_path  <- "./mo000032020.pl"
ten_header_file_path <- "./mogeo2010.pl"
ten_part1_file_path  <- "./mo000012010.pl"
ten_part2_file_path  <- "./mo000022010.pl"

```

```{r import data}
# -----------------------------
# Import the data
# -----------------------------
twenty_header <- read.delim(twenty_header_file_path, header=FALSE, colClasses="character", sep="|")
twenty_part1  <- read.delim(twenty_part1_file_path,  header=FALSE, colClasses="character", sep="|")
twenty_part2  <- read.delim(twenty_part2_file_path,  header=FALSE, colClasses="character", sep="|")
twenty_part3  <- read.delim(twenty_part3_file_path,  header=FALSE, colClasses="character", sep="|")

ten_part1  <- read.delim(ten_part1_file_path,  header=FALSE, colClasses="character", sep=",")
ten_part2  <- read.delim(ten_part2_file_path,  header=FALSE, colClasses="character", sep=",")

```

```{r import 2010}
g<-c(6,2,3,2,3,2,7,1,1,2,3,2,2,5,2,2,5,2,2,6,1,4,2,5,2,2,4,5,2,1,3,5,2,6,1,5,2,5,2,5,3,5,2,5,3,1,1,5,2,1,1,2,3,3,6,1,3,5,5,2,5,5,5,14,14,90,1,1,9,9,11,12,2,1,6,5,8,8,8,8,8,8,8,8,8,2,2,2,3,3,3,3,3,3,2,2,2,1,1,5,18)

ten_header <- read.fwf(ten_header_file_path, width=g)


```


```{r header ids}

head(ten_header)

```



```{r assign colnames for 2020}

colnames(twenty_header) <- c("FILEID", "STUSAB", "SUMLEV", "GEOVAR", "GEOCOMP", "CHARITER", "CIFSN", "LOGRECNO", "GEOID", 
  "GEOCODE", "REGION", "DIVISION", "STATE", "STATENS", "COUNTY", "COUNTYCC", "COUNTYNS", "COUSUB",
  "COUSUBCC", "COUSUBNS", "SUBMCD", "SUBMCDCC", "SUBMCDNS", "ESTATE", "ESTATECC", "ESTATENS", 
  "CONCIT", "CONCITCC", "CONCITNS", "PLACE", "PLACECC", "PLACENS", "TRACT", "BLKGRP", "BLOCK", 
  "AIANHH", "AIHHTLI", "AIANHHFP", "AIANHHCC", "AIANHHNS", "AITS", "AITSFP", "AITSCC", "AITSNS",
  "TTRACT", "TBLKGRP", "ANRC", "ANRCCC", "ANRCNS", "CBSA", "MEMI", "CSA", "METDIV", "NECTA",
  "NMEMI", "CNECTA", "NECTADIV", "CBSAPCI", "NECTAPCI", "UA", "UATYPE", "UR", "CD116", "CD118",
  "CD119", "CD120", "CD121", "SLDU18", "SLDU22", "SLDU24", "SLDU26", "SLDU28", "SLDL18", "SLDL22",
  "SLDL24", "SLDL26", "SLDL28", "VTD", "VTDI", "ZCTA", "SDELM", "SDSEC", "SDUNI", "PUMA", "AREALAND",
  "AREAWATR", "BASENAME", "NAME", "FUNCSTAT", "GCUNI", "POP100", "HU100", "INTPTLAT", "INTPTLON", 
  "LSADC", "PARTFLAG", "UGA")
colnames(twenty_part1) <- c("FILEID", "STUSAB", "CHARITER", "CIFSN", "LOGRECNO", 
                     paste0("P00", c(10001:10071, 20001:20073)))
colnames(twenty_part2) <- c("FILEID", "STUSAB", "CHARITER", "CIFSN", "LOGRECNO", 
                     paste0("P00", c(30001:30071, 40001:40073)), 
                     paste0("H00", 10001:10003))
colnames(twenty_part3) <- c("FILEID", "STUSAB", "CHARITER", "CIFSN", "LOGRECNO",
                     paste0("P00", 50001:50010))

```


```{r merge data}
# -----------------------------
# Merge the data
# -----------------------------
combine <- Reduce(function(x,y) {merge(x, y, by=c("LOGRECNO", "STUSAB", "FILEID", "CHARITER"))}, list(header[,-7], part1[,-4], part2[,-4], part3))

# -----------------------------
# Order the data
# -----------------------------
combine <- combine[order(combine$LOGRECNO), c("FILEID", "STUSAB", "SUMLEV", "GEOVAR", "GEOCOMP", "CHARITER", "CIFSN", "LOGRECNO", "GEOID", "GEOCODE", "REGION", "DIVISION", "STATE", "STATENS", "COUNTY", "COUNTYCC", "COUNTYNS", "COUSUB", "COUSUBCC", "COUSUBNS", "SUBMCD", "SUBMCDCC", "SUBMCDNS", "ESTATE", "ESTATECC", "ESTATENS", 
"CONCIT", "CONCITCC", "CONCITNS", "PLACE", "PLACECC", "PLACENS", "TRACT", "BLKGRP", "BLOCK", 
"AIANHH", "AIHHTLI", "AIANHHFP", "AIANHHCC", "AIANHHNS", "AITS", "AITSFP", "AITSCC", "AITSNS",
"TTRACT", "TBLKGRP", "ANRC", "ANRCCC", "ANRCNS", "CBSA", "MEMI", "CSA", "METDIV", "NECTA",
"NMEMI", "CNECTA", "NECTADIV", "CBSAPCI", "NECTAPCI", "UA", "UATYPE", "UR", "CD116", "CD118",
"CD119", "CD120", "CD121", "SLDU18", "SLDU22", "SLDU24", "SLDU26", "SLDU28", "SLDL18", "SLDL22",
"SLDL24", "SLDL26", "SLDL28", "VTD", "VTDI", "ZCTA", "SDELM", "SDSEC", "SDUNI", "PUMA", "AREALAND",
"AREAWATR", "BASENAME", "NAME", "FUNCSTAT", "GCUNI", "POP100", "HU100", "INTPTLAT", "INTPTLON", 
"LSADC", "PARTFLAG", "UGA", 
  paste0("P00", c(10001:10071, 20001:20073)),
  paste0("P00", c(30001:30071, 40001:40073)), 
  paste0("H00", 10001:10003), paste0("P00", 50001:50010))]
  rownames(combine) <- 1:nrow(combine)

```

```{r header info}
#slim it down
comboSlim <- select(combine, "FILEID", "SUMLEV", "LOGRECNO", "GEOID", "GEOCODE", "AREALAND",
"AREAWATR", "BASENAME", "NAME", "FUNCSTAT", "GCUNI", "POP100", "HU100", "INTPTLAT", "INTPTLON", 
"LSADC", "PARTFLAG", "PLACENS", "TRACT", "BLKGRP", "BLOCK", paste0("P00", c(10001:10071, 20001:20073)))

head(comboSlim, 125)

```

```{r filter-rows}
comboSlimCo <- comboSlim %>%
  filter(LSADC == "06")

comboSlimCo <- head(comboSlimCo, 114)

summary(comboSlimCo)

```

```{r tract filter}
pop <- select(comboSlimCo, GEOID, P0010001, P0010004)

pop$P0010001 <- as.integer(pop$P0010001)
pop$P0010004 <- as.integer(pop$P0010004)

pop <- mutate(pop, proportion = as.numeric(P0010004/P0010001))

head(pop, 15)

```

```{r histo}
ggplot(pop, aes(x=proportion)) + geom_histogram(binwidth = .005)


```


```{r ggplot-map}

missouri_counties <- counties('Missouri')

race <- geo_join(missouri_counties, pop, "GEOID", "GEOID")

#bins <- c(0, .05, .10, .15, .20, .25, .35, .50, Inf)

#assign the bins a color palette
pal <- colorBin("Blues", domain = race$proportion, 8, pretty=FALSE)

m <- leaflet(race) %>%
  setView(-92.4567826, 38.3507500, 7) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(
    fillColor = ~pal(race$proportion),
    stroke = TRUE,
    smoothFactor = 0.2,
    weight = 0.5,
    fillOpacity = 0.7,
    color = ~pal(race$proportion))%>%
  addLegend(
    position = "bottomright",
    pal = pal,
    values = race$proportion,
    title = "Proportion of Black residents.",
    opacity = 1
  )
m


```



